name: Build Angular App

on:
  push:
    branches:
      - master

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
            node-version: '18'
            registry-url: 'https://npm.pkg.github.com'
            scope: '@martapanc'
        env:
            NODE_AUTH_TOKEN: ${{ secrets.GH_REGISTRY_PACKAGES }}

      - run: yarn install && yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MPANCALDI_ANGULAR }}"
          projectId: mpancaldi-angular
          channelId: live
